/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ticket.booking;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appExists() {
        App classUnderTest = new App();
        assertNotNull("app should exist", classUnderTest);
    }
}
